version: '3'
services:
  redis4accountpool:
    image: redis:alpine
    container_name: redis4accountpool
    command: redis-server
    ports:
      - "6333:6379"
  accountpool:
    build: .
    image: 'germey/accountpool'
    container_name: accountpool
    ports:
      - "6777:6777"
    environment:
      REDIS_HOST: redis4accountpool
      REDIS_PORT: "6379"
      API_PORT: "6777"
      WEBSITE: antispider7