version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    restart: always
  accountpool:
    build: .
    image: 'germey/accountpool'
    container_name: accountpool
    ports:
      - "6777:6777"
    restart: always
    environment:
      REDIS_HOST: redis
      WEBSITE: antispider6